apiVersion: v1
kind: Service
metadata:
  name: otel-golang
  namespace: opentelemetry
spec:
  selector:
    app: otel-golang
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

# kubectl port-forward service/otel-golang 8080:8080 -n opentelemetry
# Forwarding from 127.0.0.1:8000 -> 80
# Forwarding from [::1]:8000 -> 80