apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
      # metrics
      prometheusremotewrite:
        endpoint: http://192.168.56.161:9090/api/v1/write
      # traces
      otlp/tempo:
        endpoint: http://192.168.56.161:4317
        tls:
          insecure: true
          insecure_skip_verify: true
      # opentelemetry-collector:0.83.0: error decoding 'exporters': unknown type: "loki" for id
      # logs
      #loki:
      #  endpoint: http://192.168.56.161:3100/loki/api/v1/push      
    processors:
      batch:

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging, prometheusremotewrite]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/tempo]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [logging]
          
# kubectl get svc -n opentelemetry