apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: opentelemetry
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
    processors:
      batch:

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [logging]
          
# kubectl get svc -n opentelemetry